/**
 * apps/web — __tests__/artifact-export-pptx-composed.test.ts
 *
 * Tests for Rendering V2 Phase 5: renderCarouselToPPTXComposed(),
 * isCompositionPptxEnabled(), and renderArtifactToPPTX()'s flag-gated
 * dispatch + defensive fallback for the carousel case.
 *
 * UNLIKE Phase 4's PDF tests, this sandbox CAN fully exercise this code
 * path end-to-end: pptxgenjs is a pure npm package (no external Chromium
 * binary download required), so these tests generate REAL .pptx byte
 * output and inspect it — not just a rendered string, and not just a
 * mocked call. A .pptx file is a ZIP archive of OOXML XML parts; this
 * suite unzips the actual generated bytes and asserts on the real
 * slide XML, which is a materially stronger verification than Phase 3/4's
 * HTML-string-only checks.
 */

import { describe, it, expect, afterEach } from 'vitest'
import JSZip from 'jszip'
import type { CarouselArtifact } from '@brandos/contracts'
import {
  renderArtifactToPPTX,
  renderCarouselToPPTXComposed,
  isCompositionPptxEnabled,
  type SupportedPptxArtifactType,
} from '../lib/artifact-export-pptx'

const ORIGINAL_FLAG = process.env.RENDERING_V2_COMPOSITION_PPTX

function setFlag(value: 'true' | undefined) {
  if (value === undefined) delete process.env.RENDERING_V2_COMPOSITION_PPTX
  else process.env.RENDERING_V2_COMPOSITION_PPTX = value
}

afterEach(() => {
  setFlag(ORIGINAL_FLAG as 'true' | undefined)
})

function makeCarouselArtifact(overrides?: Partial<CarouselArtifact>): CarouselArtifact {
  return {
    $schema: 'artifact-json@2.0',
    id: 'test-001',
    artifact_type: 'carousel',
    title: 'Test Carousel',
    summary: 'A test carousel',
    hook: 'This is the hook',
    cta: 'This is the CTA',
    semantic_theme: { visual_preset: 'social' },
    audience: { sophistication: 'practitioner' },
    narrative_arc: {
      structure: 'problem-solution',
      hook_statement: 'hook',
      thesis: 'thesis',
      resolution: 'resolution',
      pacing: 'balanced',
    },
    richness_metrics: {
      overall_score: 80,
      density_score: 80,
      evidence_score: 80,
      persuasion_score: 80,
      cta_quality_score: 80,
      narrative_coherence_score: 80,
      hook_strength_score: 80,
      audience_alignment_score: 80,
      total_content_words: 100,
      avg_words_per_unit: 50,
    },
    generation_trace: {
      generated_at: '2026-01-01T00:00:00.000Z',
      ocl_strategy: 'direct',
      governance_outcome: 'passed',
      repair_attempts: 0,
      input_type: 'json',
    },
    export_metadata: { available_formats: [] },
    created_at: '2026-01-01T00:00:00.000Z',
    carousel_meta: { palette: [], slide_count: 1 },
    slides: [{ slide: 1, role: 'hook', headline: 'Test headline', body: 'Test body content.' }],
    ...overrides,
  }
}

/** Unzips a .pptx buffer and returns the raw XML text of every slideN.xml part, in slide order. */
async function extractSlideXml(bytes: Buffer): Promise<string[]> {
  const zip = await JSZip.loadAsync(bytes)
  const slideFiles = Object.keys(zip.files)
    .filter((name) => /^ppt\/slides\/slide\d+\.xml$/.test(name))
    .sort((a, b) => {
      const numA = parseInt(a.match(/slide(\d+)\.xml/)![1]!, 10)
      const numB = parseInt(b.match(/slide(\d+)\.xml/)![1]!, 10)
      return numA - numB
    })
  return Promise.all(slideFiles.map((name) => zip.files[name]!.async('text')))
}

describe('isCompositionPptxEnabled', () => {
  it('is false when unset, true only when exactly "true"', () => {
    setFlag(undefined)
    expect(isCompositionPptxEnabled()).toBe(false)
    setFlag('true')
    expect(isCompositionPptxEnabled()).toBe(true)
  })
})

describe('renderCarouselToPPTXComposed — real .pptx output, unzipped and inspected', () => {
  it('produces a valid ZIP with the expected number of slides (title + 1 slide + CTA)', async () => {
    const result = await renderCarouselToPPTXComposed(makeCarouselArtifact())
    expect(result.mimeType).toBe('application/vnd.openxmlformats-officedocument.presentationml.presentation')
    const slides = await extractSlideXml(result.bytes)
    expect(slides).toHaveLength(3) // title slide, 1 content slide, CTA slide
  })

  it('includes the title, hook, and headline text in the real slide XML', async () => {
    const result = await renderCarouselToPPTXComposed(makeCarouselArtifact())
    const slides = await extractSlideXml(result.bytes)
    const allText = slides.join('\n')
    expect(allText).toContain('Test Carousel')
    expect(allText).toContain('This is the hook')
    expect(allText).toContain('Test headline')
    expect(allText).toContain('Test body content.')
    expect(allText).toContain('This is the CTA')
  })

  it("resolves the 'social' preset's accent color into the real slide XML fill/color values", async () => {
    const result = await renderCarouselToPPTXComposed(
      makeCarouselArtifact({ semantic_theme: { visual_preset: 'social' } })
    )
    const slides = await extractSlideXml(result.bytes)
    // 'social' preset's accent color in @brandos/design-tokens is #ec4899 → EC4899 (no '#', uppercase, pptxgenjs convention)
    expect(slides.join('\n').toUpperCase()).toContain('EC4899')
  })

  it("produces a two-column ('split') slide with the headline and body positioned at different x offsets", async () => {
    const result = await renderCarouselToPPTXComposed(
      makeCarouselArtifact({
        slides: [{ slide: 1, role: 'framework', headline: 'Framework headline', body: 'Body text', layout_hint: 'split' }],
      })
    )
    const slides = await extractSlideXml(result.bytes)
    const contentSlide = slides[1]! // slide 0 = title, slide 1 = the one carousel slide
    // Extract every <a:off x="..."/> offset value present on this slide — a
    // real structural check, not a string-contains check: 'split' must
    // place shapes at genuinely different x-coordinates, not just claim to.
    const xOffsets = [...contentSlide.matchAll(/<a:off x="(\d+)"/g)].map((m) => parseInt(m[1]!, 10))
    const uniqueXOffsets = new Set(xOffsets)
    expect(uniqueXOffsets.size).toBeGreaterThan(1)
  })

  it('never renders speaker_notes text onto the visible slide', async () => {
    const result = await renderCarouselToPPTXComposed(
      makeCarouselArtifact({
        slides: [{ slide: 1, role: 'hook', headline: 'H', speaker_notes: 'SECRET_PRESENTER_NOTES_XYZ' }],
      })
    )
    const slides = await extractSlideXml(result.bytes)
    expect(slides.join('\n')).not.toContain('SECRET_PRESENTER_NOTES_XYZ')
  })

  it('emphasis_keywords produce a separate bold text run in the real XML, not just plain text', async () => {
    const result = await renderCarouselToPPTXComposed(
      makeCarouselArtifact({
        slides: [{ slide: 1, role: 'hook', headline: 'Revenue grew 40 percent', emphasis_keywords: ['40 percent'] }],
      })
    )
    const slides = await extractSlideXml(result.bytes)
    const contentSlide = slides[1]!
    // A bold run (<a:b val="1"/>) must exist somewhere in the content slide's
    // run properties for the emphasized text to render distinctly.
    expect(contentSlide).toMatch(/<a:rPr[^>]*b="1"/)
  })
})

describe('renderArtifactToPPTX — carousel dispatch (real output)', () => {
  it('uses the legacy renderer when the flag is off', async () => {
    setFlag(undefined)
    const result = await renderArtifactToPPTX(makeCarouselArtifact() as unknown as Record<string, unknown>, 'carousel')
    const slides = await extractSlideXml(result.bytes)
    // Legacy renderer's title-slide accent bar uses '0EA5E9' regardless of
    // theme — a signature that only appears on the pre-Phase-5 path.
    expect(slides.join('\n').toUpperCase()).toContain('0EA5E9')
  })

  it('uses the Composition Layer renderer when the flag is on', async () => {
    setFlag('true')
    const result = await renderArtifactToPPTX(
      makeCarouselArtifact({ semantic_theme: { visual_preset: 'social' } }) as unknown as Record<string, unknown>,
      'carousel'
    )
    const slides = await extractSlideXml(result.bytes)
    expect(slides.join('\n').toUpperCase()).toContain('EC4899') // social preset accent
  })

  it('falls back to the legacy renderer if the composed path throws on malformed input', async () => {
    setFlag('true')
    const malformed = { ...makeCarouselArtifact(), slides: undefined } as unknown as Record<string, unknown>
    await expect(renderArtifactToPPTX(malformed, 'carousel')).resolves.toBeDefined()
    const result = await renderArtifactToPPTX(malformed, 'carousel')
    expect(result.mimeType).toBe('application/vnd.openxmlformats-officedocument.presentationml.presentation')
  })

  it('deck/report dispatch is unaffected by the flag (Phase 5 is carousel-only)', async () => {
    setFlag('true')
    const deckArtifact = { artifact_type: 'deck' as SupportedPptxArtifactType, title: 'A Deck', slides: [] }
    const result = await renderArtifactToPPTX(deckArtifact, 'deck')
    expect(result.mimeType).toBe('application/vnd.openxmlformats-officedocument.presentationml.presentation')
  })
})
