/**
 * apps/web — lib/artifact-export-pdf-template.ts
 *
 * RENDERING V2 — PHASE 4: independent PDF template (carousel only).
 * See RENDERING_ARCHITECTURE_V2.md §4.1, RENDERING_ROADMAP_V2.md Phase 4.
 *
 * ARCHITECTURE DECISION, changed from the pre-Phase-4 state:
 *   Before this phase, PDF was generated by printing the SAME HTML the
 *   on-screen export produces (artifact-export-html.ts's
 *   renderArtifactToHTML), relying on one shared `@media print` block to
 *   adapt it for paper. RENDERING_ARCHITECTURE_AUDIT.md Finding H-1
 *   identified this as the root cause of PDF's page-break/pagination
 *   problems: one DOM trying to serve two physically incompatible media
 *   (infinite-scroll screen vs. fixed-size page) via a handful of color-swap
 *   CSS overrides has no way to know where a physical page boundary falls.
 *
 *   This module is a SEPARATE, print-specific template — same
 *   CompositionDocument input (via composeArtifact()), different markup and
 *   CSS tuned for a physical page: its own type scale interpretation (points,
 *   not the screen template's pixels — see TYPE SCALE UNITS note below), its
 *   own margins, and REAL per-unit page-break control driven by
 *   CompositionUnit.pageBreak (RENDERING_ARCHITECTURE_V2.md §4.1) instead of
 *   one blanket rule. Still rendered via headless Chromium Print-to-PDF
 *   (see artifact-export-pdf.ts) — this is a second TEMPLATE, not a second
 *   PDF ENGINE; the architecture decision to stay on Chromium rather than
 *   move to pdf-lib-style primitive drawing is unchanged and still correct
 *   (see artifact-export-pdf.ts's own header for that rationale).
 *
 * TYPE SCALE UNITS — an intentional per-format interpretation, not a bug:
 *   @brandos/design-tokens' TypeScale values are documented as "a
 *   renderer-neutral unit (points) — renderers convert to their own unit."
 *   Phase 3's screen HTML renderer (artifact-export-html.ts) interpreted
 *   them as CSS px for on-screen sizing. This template interprets the SAME
 *   numeric scale as CSS pt (points) — the native print measurement unit —
 *   which is the more literal reading of "points" for a physical page.
 *   Different formats are explicitly allowed to interpret a shared
 *   renderer-neutral value differently (RENDERER_CONTRACT.md §2: "format-
 *   specific typography... rules" are renderer-owned) — flagged here so a
 *   future reader comparing the two templates' CSS doesn't mistake this for
 *   an inconsistency.
 *
 * SCOPE: carousel only, mirroring Phase 3's scope decision (one complete
 * vertical slice over four partial ones). Deck/report/newsletter PDF
 * exports are UNCHANGED — they still go through the pre-Phase-4 path
 * (renderArtifactToHTML + shared @media print), regardless of the flag.
 *
 * PAGE-BREAK GUARANTEE, stated honestly: CSS `break-inside: avoid` (used for
 * CompositionUnit.pageBreak === 'avoid') is a REQUEST to the rendering
 * engine, not a hard guarantee per the CSS Fragmentation spec — a browser
 * may still break inside an element if its content cannot possibly fit
 * within one page even alone (e.g. a single slide with an unusually large
 * amount of text). This module does not attempt to detect or truncate that
 * case; it asks correctly and accepts the browser's fallback behavior if the
 * content genuinely doesn't fit, same as every other CSS-fragmentation-based
 * PDF pipeline. TESTING NOTE: this sandbox has no Chromium binary (see
 * artifact-export-pdf.ts's own "KNOWN GAP" header comment) — the CSS emitted
 * here is verified by string-content tests only; actual page-break behavior
 * as rendered by a real browser is NOT verified in this environment.
 */

import type { CarouselArtifact } from '@brandos/contracts'
import {
  composeArtifact,
  type CompositionBlock,
  type CompositionUnit,
  type ResolvedTheme,
  type PageBreakPolicy,
} from '@brandos/composition-layer'
import { escapeHtml } from './artifact-export-html'

/** Exported for tests — mirrors isCompositionHtmlEnabled()'s pattern in artifact-export-html.ts. */
export function isCompositionPdfEnabled(): boolean {
  return process.env.RENDERING_V2_COMPOSITION_PDF === 'true'
}

function pageBreakStyle(policy: PageBreakPolicy): string {
  switch (policy) {
    case 'avoid':
      // Both properties: `break-inside` is the modern CSS Fragmentation
      // property; `page-break-inside` is the legacy alias some print engines
      // (including older Chromium print paths) still key off. Emitting both
      // is defensive, not redundant-by-mistake.
      return 'break-inside:avoid;page-break-inside:avoid;'
    case 'always':
      return 'break-before:page;page-break-before:always;'
    case 'auto':
    default:
      return ''
  }
}

function themeToPrintCssVars(theme: ResolvedTheme): string {
  // Print-specific margins/padding — deliberately tighter than the screen
  // template's spacing tokens, since a physical page has a fixed, small
  // budget compared to an infinite-scroll screen. Colors are still taken
  // from the resolved theme (Findings C-2/P-1 apply here too), but the
  // @media print override below still forces light-on-dark → light
  // background for ink/toner reasons, same as the legacy template did.
  return [
    `--color-primary:${theme.palette.primary}`,
    `--color-accent:${theme.palette.accent}`,
    `--text-primary:#111111`,
    `--text-secondary:#444444`,
    `--font-title:${theme.typography.titleFont}`,
    `--font-body:${theme.typography.bodyFont}`,
    // Interpreted as pt here — see this file's header "TYPE SCALE UNITS" note.
    `--type-h1:${theme.typography.scale.h1}pt`,
    `--type-h2:${theme.typography.scale.h2}pt`,
    `--type-body:${theme.typography.scale.body}pt`,
    `--type-caption:${theme.typography.scale.caption}pt`,
  ].join(';')
}

function renderPrintBlock(block: CompositionBlock, accentColor: string): string {
  switch (block.kind) {
    case 'heading': {
      const size = block.level === 1 ? 'var(--type-h1)' : block.level === 2 ? 'var(--type-h2)' : 'var(--type-caption)'
      return `<h${block.level} style="font-family:var(--font-title);font-size:${size};color:var(--text-primary);margin:0 0 8pt;line-height:1.3;">${escapeHtml(block.text)}</h${block.level}>`
    }
    case 'body':
      return `<p style="font-family:var(--font-body);font-size:var(--type-body);color:var(--text-secondary);margin:0 0 8pt;line-height:1.5;">${escapeHtml(block.text)}</p>`
    case 'bullets':
      return `<ul style="margin:0 0 8pt;padding-left:14pt;">${block.items
        .map((b) => `<li style="font-size:var(--type-body);color:var(--text-secondary);margin-bottom:4pt;line-height:1.4;">${escapeHtml(b)}</li>`)
        .join('')}</ul>`
    case 'callout': {
      const label = block.variant === 'insight' ? 'Key Insight' : block.variant === 'takeaway' ? 'Takeaway' : 'Quote'
      return `<div style="margin:8pt 0;padding:8pt 10pt;border-left:2pt solid ${accentColor};background:#f7f7f7;">
        <p style="font-size:8pt;font-weight:700;color:${accentColor};text-transform:uppercase;margin:0 0 3pt;">${label}</p>
        <p style="font-size:var(--type-body);color:var(--text-primary);margin:0;line-height:1.4;">${escapeHtml(block.text)}</p>
      </div>`
    }
    case 'evidence-list':
      return `<div style="margin-top:6pt;">
        <p style="font-size:7pt;font-weight:700;color:var(--text-secondary);text-transform:uppercase;margin:0 0 3pt;">Evidence</p>
        <ul style="margin:0;padding-left:12pt;">${block.items
          .map((e) => `<li style="font-size:var(--type-caption);color:var(--text-secondary);margin-bottom:3pt;">${escapeHtml(e)}</li>`)
          .join('')}</ul>
      </div>`
    case 'stat-row':
      return `<div style="display:flex;gap:16pt;margin:6pt 0;">${block.stats
        .map(
          (s) =>
            `<div><div style="font-size:16pt;font-weight:900;color:${accentColor};">${escapeHtml(s.value)}</div><div style="font-size:7pt;color:var(--text-secondary);text-transform:uppercase;">${escapeHtml(s.label)}</div></div>`
        )
        .join('')}</div>`
    case 'speaker-notes':
      // Never printed — presentation-only content, same convention as the
      // screen renderer (see artifact-export-html.ts's renderCompositionBlock).
      return ''
  }
}

function renderPrintUnit(unit: CompositionUnit, accentColor: string, idx: number): string {
  const blocksHtml = unit.blocks.map((b) => renderPrintBlock(b, accentColor)).join('\n')
  return `
    <section style="
      ${pageBreakStyle(unit.pageBreak)}
      border:0.5pt solid #cccccc;
      border-radius:4pt;
      padding:14pt;
      margin-bottom:12pt;
    ">
      <div style="font-size:7pt;font-weight:700;color:${accentColor};text-transform:uppercase;letter-spacing:0.05em;margin-bottom:8pt;">
        ${escapeHtml(unit.role.toUpperCase())} · ${idx + 1}
      </div>
      ${blocksHtml}
    </section>`
}

/**
 * Print-specific carousel template. Same CompositionDocument as
 * renderCarouselToHTMLComposed() (Phase 3) — different markup/CSS tuned for
 * a physical page rather than a screen. See this file's header for the full
 * rationale.
 */
export function renderCarouselToPrintHTML(artifact: CarouselArtifact): string {
  const doc = composeArtifact(artifact)
  const title = artifact.title || 'Carousel'

  const unitsHtml = doc.units.map((unit, idx) => renderPrintUnit(unit, doc.theme.palette.accent, idx)).join('\n')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${escapeHtml(title)} — BrandOS Carousel (Print)</title>
  <style>
    :root { ${themeToPrintCssVars(doc.theme)} }
    *, *::before, *::after { box-sizing: border-box; }
    @page { size: A4; margin: 12mm 10mm; }
    body {
      font-family: var(--font-body);
      color: var(--text-primary);
      background: #ffffff;
      margin: 0;
    }
    .doc-header { margin-bottom: 14pt; padding-bottom: 8pt; border-bottom: 1pt solid #dddddd; }
    .doc-title { font-family: var(--font-title); font-size: 20pt; font-weight: 800; margin: 0 0 4pt; color: var(--text-primary); }
    .doc-hook { font-size: 9pt; color: var(--text-secondary); margin: 0; font-style: italic; }
    .doc-cta { margin-top: 10pt; padding: 8pt 10pt; border: 0.5pt solid var(--color-accent); border-radius: 4pt; text-align: center; }
    .doc-cta p { font-size: 9pt; font-weight: 700; color: var(--color-primary); margin: 0; }
  </style>
</head>
<body>
  <div class="doc-header">
    <h1 class="doc-title">${escapeHtml(title)}</h1>
    ${artifact.hook ? `<p class="doc-hook">${escapeHtml(artifact.hook)}</p>` : ''}
  </div>

  ${unitsHtml}

  ${artifact.cta ? `<div class="doc-cta"><p>${escapeHtml(artifact.cta)}</p></div>` : ''}
</body>
</html>`
}
