/**
 * apps/web — lib/artifact-export-pdf.ts
 *
 * PDF export for ArtifactV2 (carousel | deck | report).
 *
 * ARCHITECTURE DECISION:
 *   PDF is generated by printing the SAME HTML the html export branch
 *   already produces (renderArtifactToHTML from artifact-export-html.ts)
 *   through headless Chromium's native "Print to PDF". This is a
 *   deliberate choice to avoid a second, divergent rendering pipeline:
 *     - One source of visual truth per artifact type (the HTML renderer).
 *     - PDF and HTML exports are guaranteed to match pixel-for-pixel.
 *     - The existing `@media print` CSS rules in each HTML renderer
 *       (light background, avoid mid-element page breaks) take effect
 *       automatically because Chromium's PDF print path runs print media.
 *   The alternative (drawing a PDF from scratch with pdf-lib/reportlab-
 *   style primitives) would mean re-implementing every layout decision
 *   already made in artifact-export-html.ts a second time, and the two
 *   would drift the first time either one changes. Rejected for that
 *   reason — see PPTX export's own module for why that one DOES need a
 *   from-scratch renderer (PPTX has no HTML-equivalent print path).
 *
 * RUNTIME ENVIRONMENT:
 *   - Local dev: uses puppeteer-core pointed at a locally installed
 *     Chrome/Chromium (CHROME_EXECUTABLE_PATH env override, or common
 *     default install paths).
 *   - Production / serverless (Vercel, AWS Lambda, etc.): uses
 *     @sparticuz/chromium, the standard serverless-compatible Chromium
 *     binary + launch args for puppeteer-core. This is the conventional
 *     pairing for "render HTML to PDF" in a Next.js API route — it does
 *     NOT bundle a full desktop Chromium download (incompatible with
 *     most serverless deployment size limits), and does not require any
 *     change to the existing deployment pipeline beyond the npm package.
 *
 * KNOWN GAP (surfaced honestly, not papered over):
 *   This module's actual Chromium launch + PDF byte output is NOT
 *   exercised by an automated test in this sprint — the sandbox this was
 *   written in has no network access to a Chromium binary download
 *   (puppeteer's bundled-Chromium install and @sparticuz/chromium's
 *   runtime binary are both fetched from storage.googleapis.com, which
 *   is outside this environment's allowed domains). The HTML generation
 *   it wraps (renderArtifactToHTML) IS independently verified — see
 *   artifact-export-html.test coverage. The launch path itself should be
 *   smoke-tested in a real dev/CI environment with network access before
 *   this is considered fully verified end-to-end. Flagged in the
 *   completion report's Remaining Risks.
 */

import type { SupportedHtmlArtifactType } from './artifact-export-html'
import { renderArtifactToHTML } from './artifact-export-html'

// puppeteer-core has no bundled browser — works identically in dev and
// serverless, only the executable path + launch args differ.
import type { Browser } from 'puppeteer-core'

export interface PdfExportResult {
  bytes: Buffer
  mimeType: 'application/pdf'
}

/**
 * Resolve a Chromium executable path + launch args for the current
 * environment. Serverless first (the common deployment target), with a
 * cross-platform local-dev fallback for `next dev`.
 *
 * Resolution order:
 *   1. Explicit override — CHROME_EXECUTABLE_PATH env var (any platform)
 *   2. Serverless environments — @sparticuz/chromium (Vercel, Lambda, GCR, Railway…)
 *   3. Local dev — platform-specific default install paths
 *      macOS:   /Applications/Google Chrome.app/…
 *      Linux:   /usr/bin/google-chrome, /usr/bin/chromium-browser,
 *               /usr/bin/chromium, /snap/bin/chromium
 *      Windows: %PROGRAMFILES%\Google\Chrome\Application\chrome.exe
 *               %PROGRAMFILES(X86)%\Google\Chrome\Application\chrome.exe
 *               %LOCALAPPDATA%\Google\Chrome\Application\chrome.exe  (per-user)
 *               %PROGRAMFILES(X86)%\Microsoft\Edge\Application\msedge.exe (fallback)
 *               %PROGRAMFILES%\Microsoft\Edge\Application\msedge.exe
 *
 * CHROME_EXECUTABLE_PATH is checked before the serverless heuristic so that
 * a developer pointing at a local binary always wins, regardless of whether
 * NODE_ENV=production is set (common in Docker-based local stacks).
 *
 * puppeteer vs puppeteer-core: this module requires puppeteer-core only.
 * puppeteer (the full package, which auto-downloads Chromium) is not a
 * dependency — do not add it. puppeteer-core works identically but requires
 * an explicit executablePath, which is what this function provides.
 */
async function resolveBrowserLaunchOptions(): Promise<{
  executablePath: string
  args: string[]
  headless: boolean
}> {
  const { existsSync } = await import('fs')

  // ── 0. Always-win explicit override ────────────────────────────────────────
  // Set CHROME_EXECUTABLE_PATH to any Chromium-compatible binary.
  // Takes precedence over serverless detection so Docker/CI stacks that set
  // NODE_ENV=production but run a local binary don't accidentally try to
  // fetch @sparticuz/chromium.
  if (process.env.CHROME_EXECUTABLE_PATH) {
    const override = process.env.CHROME_EXECUTABLE_PATH
    if (!existsSync(override)) {
      throw new Error(
        `[pdf-export] CHROME_EXECUTABLE_PATH is set but the file does not exist: "${override}". ` +
        `Check the path and try again.`
      )
    }
    return { executablePath: override, args: [], headless: true }
  }

  // ── 1. Serverless / production environments ─────────────────────────────────
  // @sparticuz/chromium is a pre-built, Lambda/Vercel-compatible Chromium binary.
  // It is the standard pairing with puppeteer-core in serverless deployments.
  // Detected by any of the common serverless platform markers.
  const isServerless =
    process.env.VERCEL === '1' ||
    process.env.AWS_LAMBDA_FUNCTION_NAME != null ||
    process.env.LAMBDA_TASK_ROOT != null ||
    process.env.GOOGLE_CLOUD_RUN_JOB != null ||
    process.env.K_SERVICE != null ||            // Google Cloud Run services
    process.env.RAILWAY_ENVIRONMENT != null ||
    process.env.FLY_APP_NAME != null

  if (isServerless) {
    try {
      const chromium = (await import('@sparticuz/chromium')).default
      return {
        executablePath: await chromium.executablePath(),
        args: chromium.args,
        headless: true,
      }
    } catch (err: unknown) {
      throw new Error(
        '[pdf-export] Running in a serverless environment but @sparticuz/chromium failed to load. ' +
        'Ensure "@sparticuz/chromium" is listed in dependencies and the deployment includes it. ' +
        `Underlying error: ${err instanceof Error ? err.message : String(err)}`
      )
    }
  }

  // ── 2. Local dev — cross-platform path scan ─────────────────────────────────
  // Build the candidate list based on the current platform so the error
  // message only shows paths that are plausible for the developer's OS.

  const isWindows = process.platform === 'win32'
  const isMac     = process.platform === 'darwin'

  // Windows: resolve env vars at runtime so the paths work regardless of the
  // user account name or whether Chrome was installed system-wide or per-user.
  const winProgramFiles    = process.env['PROGRAMFILES']      ?? 'C:\\Program Files'
  const winProgramFilesX86 = process.env['PROGRAMFILES(X86)'] ?? 'C:\\Program Files (x86)'
  const winLocalAppData    = process.env['LOCALAPPDATA']      ?? ''

  const candidatePaths: string[] = isWindows
    ? [
        // System-wide Chrome (64-bit and 32-bit installers)
        `${winProgramFiles}\\Google\\Chrome\\Application\\chrome.exe`,
        `${winProgramFilesX86}\\Google\\Chrome\\Application\\chrome.exe`,
        // Per-user Chrome install (most common on corporate machines)
        ...(winLocalAppData
          ? [`${winLocalAppData}\\Google\\Chrome\\Application\\chrome.exe`]
          : []),
        // Microsoft Edge — always present on Windows 10/11, Chromium-based
        `${winProgramFilesX86}\\Microsoft\\Edge\\Application\\msedge.exe`,
        `${winProgramFiles}\\Microsoft\\Edge\\Application\\msedge.exe`,
      ]
    : isMac
    ? [
        '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
        '/Applications/Chromium.app/Contents/MacOS/Chromium',
        '/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge',
      ]
    : [
        // Linux — package-manager installs and Snap
        '/usr/bin/google-chrome',
        '/usr/bin/google-chrome-stable',
        '/usr/bin/chromium-browser',
        '/usr/bin/chromium',
        '/snap/bin/chromium',
        '/usr/bin/microsoft-edge',
      ]

  const found = candidatePaths.find(p => existsSync(p))

  if (!found) {
    const platformHint = isWindows
      ? 'Install Google Chrome (https://www.google.com/chrome/) or ensure ' +
        'Microsoft Edge is present (built into Windows 10/11).'
      : isMac
      ? 'Install Google Chrome (https://www.google.com/chrome/) or Chromium.'
      : 'Install Google Chrome: `apt install google-chrome-stable` or `snap install chromium`.'

    throw new Error(
      `[pdf-export] No Chrome/Chromium binary found for local PDF export (platform: ${process.platform}).\n` +
      `  ${platformHint}\n` +
      `  Or set the CHROME_EXECUTABLE_PATH environment variable to any Chromium-compatible binary.\n` +
      `  Locations checked:\n` +
      candidatePaths.map(p => `    • ${p}`).join('\n')
    )
  }

  return { executablePath: found, args: [], headless: true }
}

/**
 * Render an artifact (already-resolved Record shape, same input the HTML
 * branch receives) to PDF bytes via headless Chromium print-to-PDF.
 */
export async function renderArtifactToPDF(
  artifact: Record<string, unknown>,
  artifactType: SupportedHtmlArtifactType
): Promise<PdfExportResult> {
  const html = renderArtifactToHTML(artifact, artifactType)

  const puppeteer = await import('puppeteer-core')
  const { executablePath, args, headless } = await resolveBrowserLaunchOptions()

  let browser: Browser | null = null
  try {
    browser = await puppeteer.launch({ executablePath, args, headless })
    const page = await browser.newPage()

    // setContent + 'load': the HTML is fully self-contained (inline styles,
    // no external assets, no navigation request), so 'load' resolves
    // immediately. Note: setContent's WaitForOptions type deliberately
    // excludes 'networkidle0'/'networkidle2' — those track network activity
    // following a real navigation (page.goto), which setContent never
    // performs; 'load' is the correct and sufficient option here.
    await page.setContent(html, { waitUntil: 'load' })

    // Emulate print media so each renderer's `@media print` rules apply —
    // this is the entire reason PDF and HTML exports stay visually
    // consistent without a second style sheet.
    await page.emulateMediaType('print')

    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '12mm', bottom: '12mm', left: '10mm', right: '10mm' },
    })

    return { bytes: Buffer.from(pdfBuffer), mimeType: 'application/pdf' }
  } finally {
    await browser?.close()
  }
}
