/**
 * @brandos/contracts — runtime-trace.ts
 *
 * RUNTIME VERIFICATION TRACE CONTRACT
 *
 * PURPOSE:
 *   RuntimeTrace is the single canonical, structured result shape emitted by
 *   every endpoint under `/api/internal/runtime-verify/*` (Runtime Verification
 *   V2 — see scripts/platform-runtime-verify.ps1 and AGENT_CONTEXT.md for
 *   @brandos/web). Each verification endpoint (provider, model, brand-memory,
 *   governance, persistence, diagnostics) populates the subset of fields
 *   relevant to what it checked and leaves the rest undefined.
 *
 *   The verifier (PowerShell, CI, or any future client) reads RuntimeTrace
 *   objects rather than parsing ad-hoc per-endpoint shapes — this is what
 *   makes runtime verification machine-checkable instead of log-scraping.
 *
 * DESIGN INVARIANTS:
 *   - RuntimeTrace describes ACTUAL observed runtime behavior, never intent
 *     or configuration. `provider`/`model` are what served the request, not
 *     what was configured to serve it (see ai-runtime-layer's
 *     configuredModel/resolvedModel distinction for that comparison — a
 *     verification endpoint may report both, but RuntimeTrace.model is always
 *     "what actually ran").
 *   - `provider`/`model` remain the original required fields for backward
 *     compatibility with every endpoint written before this revision.
 *     `resolvedProvider`/`resolvedModel` are explicit aliases of the same
 *     values — added so the field names match what a trace consumer expects
 *     to find next to `configuredProvider`/`configuredModel` without having
 *     to know the historical `provider`/`model` names too.
 *   - Every RuntimeTrace is self-describing: requestId + checkedAt let traces
 *     be correlated across endpoints and across CI runs without an external
 *     index.
 *   - Optional fields are optional because not every check exercises every
 *     subsystem (e.g. a provider-only check never touches governance, so
 *     governanceScore stays undefined rather than a misleading 0).
 *   - This contract is intentionally flat — it is a leaf record, not a tree.
 *     Richer structured detail (violations, recommendations, etc.) belongs in
 *     the endpoint-specific response payload alongside the trace, not folded
 *     into the trace itself.
 *
 * DATA FLOW:
 *   apps/web internal verify route handler
 *     → delegates to a verification service (e.g. RuntimeVerifyService)
 *     → service drives the real runtime (ai-runtime-layer / control-plane-layer)
 *     → service builds a RuntimeTrace from what actually happened
 *     → route responds with { trace: RuntimeTrace, ...domainSpecificFields }
 *     → scripts/platform-runtime-verify.ps1 reads `trace` to assert pass/fail
 *
 * VALIDATION (added for the production-grade evolution of Runtime
 * Verification V2 — see validateRuntimeTrace() below):
 *   A trace can be well-formed JSON and still be a poor trace — e.g.
 *   `fallbackUsed: false` while `configuredProvider !== resolvedProvider` is
 *   an internally inconsistent trace, not just an incomplete one.
 *   validateRuntimeTrace() checks both presence (are the fields a
 *   production-grade trace is expected to carry actually there?) and
 *   consistency (do the fields that ARE there agree with each other?),
 *   returning WARN-level issues for missing fields and FAIL-level issues for
 *   genuine contradictions, each with a human-readable explanation — never a
 *   bare boolean.
 *
 * ZERO CIRCULAR DEPS:
 *   This file imports only from './airuntime-types' (RuntimeMode), itself
 *   zero-dependency. No @brandos/* imports anywhere in this file.
 */

import type { RuntimeMode } from './airuntime-types'

// ─── RuntimeTrace ──────────────────────────────────────────────────────────────

/**
 * RuntimeTrace — canonical structured outcome of one runtime-verification check.
 *
 * Emitted by every `/api/internal/runtime-verify/*` endpoint. Fields beyond
 * `requestId`/`checkedAt`/`provider`/`model`/`brandMemoryApplied` are optional
 * and populated only when the corresponding subsystem was exercised by the
 * check that produced this trace.
 */
export interface RuntimeTrace {
  /**
   * Correlates this trace to one verification call. Generated by the
   * verifying endpoint (not the caller) so every trace is independently
   * identifiable in logs and in the generated runtime-verification report.
   */
  requestId: string

  /**
   * ISO-8601 timestamp of when this trace was captured (end of the traced
   * operation, not the start — durationMs/executionLatency gives the
   * elapsed time).
   */
  checkedAt: string

  /**
   * The AI provider that actually served the traced request (e.g.
   * 'anthropic', 'openai'). This is the OBSERVED provider, never the
   * configured one — if the runtime fell back to a secondary provider,
   * this field reflects the fallback, not the primary. Kept as the
   * historical required field; identical to `resolvedProvider`.
   */
  provider: string

  /**
   * The model that actually served the traced request. Observed, not
   * configured. Kept as the historical required field; identical to
   * `resolvedModel`.
   */
  model: string

  /**
   * The provider the runtime was CONFIGURED to use for this request,
   * before any fallback. Compare against `resolvedProvider` to detect
   * silent fallback. Absent when the check never resolved a configured
   * value (e.g. a pure persistence check).
   */
  configuredProvider?: string

  /** Explicit alias of `provider` — see DESIGN INVARIANTS above. */
  resolvedProvider?: string

  /**
   * The model the runtime was CONFIGURED to use for this request, before
   * any fallback. Compare against `resolvedModel` to detect propagation
   * failures.
   */
  configuredModel?: string

  /** Explicit alias of `model` — see DESIGN INVARIANTS above. */
  resolvedModel?: string

  /**
   * Whether the runtime fell back away from the configured provider for
   * this request (circuit breaker, rate limit, provider error, etc.).
   * Should be `true` whenever `configuredProvider !== resolvedProvider`,
   * and `false` when they match — validateRuntimeTrace() checks this
   * consistency.
   */
  fallbackUsed?: boolean

  /**
   * Local vs cloud execution mode in effect for this trace, when known.
   * Absent when the check did not resolve a runtime mode (e.g. a pure
   * persistence check that never invoked the AI runtime).
   */
  runtimeMode?: RuntimeMode

  /**
   * Whether Brand Memory / Brand Intelligence was applied while producing
   * the traced output. Always present (true/false) on any trace that ran
   * a generation — false is meaningful (Brand Memory OFF path), not absent.
   */
  brandMemoryApplied: boolean

  /**
   * The brand identity schema/version applied, when Brand Memory was active.
   * Absent when brandMemoryApplied is false.
   */
  identityVersion?: string

  /**
   * Final governance score (0–100) assigned to the generated artifact, when
   * the traced operation ran governance evaluation. Absent for checks that
   * never reached governance (e.g. a provider-only or persistence-only check).
   */
  governanceScore?: number

  /**
   * Number of governance repair attempts consumed by the traced operation.
   * Bounded by MAX_REPAIR_ATTEMPTS (see runtime_trace.generated.md — currently
   * 3). Absent when governance did not run.
   */
  repairAttempts?: number

  /**
   * Whether the resulting artifact and/or its metadata were persisted to the
   * database during the traced operation. Absent when persistence was out of
   * scope for the check (e.g. a provider-only check that never reached the
   * artifact pipeline). Kept as the historical boolean field; see
   * `persistenceStatus` for the richer enum.
   */
  artifactPersisted?: boolean

  /**
   * Richer persistence outcome than `artifactPersisted` alone:
   *   - 'persisted'     — write + read-back both succeeded
   *   - 'failed'        — a write or read-back was attempted and failed
   *   - 'not_persisted' — persistence was attempted but the artifact was
   *                       rejected upstream (e.g. governance rejection)
   *                       before a write was attempted
   *   - 'not_applicable' — persistence was out of scope for this check
   * Absent only when the check predates this field; new checks should
   * always set it. validateRuntimeTrace() checks it agrees with
   * `artifactPersisted`.
   */
  persistenceStatus?: 'persisted' | 'failed' | 'not_persisted' | 'not_applicable'

  /**
   * The artifact schema version of the generated artifact, when one was
   * produced — sourced from `BaseArtifact.$schema` (e.g. 'artifact-json@2.0').
   * Absent when no artifact was produced during this check.
   */
  schemaVersion?: string

  /**
   * Identifies which build/version of the BrandOS runtime produced this
   * trace — sourced from `BRANDOS_RUNTIME_VERSION` if set, else the
   * `@brandos/control-plane-layer` package version, else 'unknown'. Lets a
   * report distinguish "this changed because the runtime changed" from
   * "this changed for some other reason" across CI runs.
   */
  runtimeVersion?: string

  /**
   * Wall-clock duration of the traced operation, in milliseconds. Kept as
   * the historical field name; identical to `executionLatency`.
   */
  durationMs?: number

  /** Explicit alias of `durationMs`, named to match the Part 3 field list. */
  executionLatency?: number
}


// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * createRuntimeTrace — factory for a RuntimeTrace with requestId/checkedAt
 * stamped automatically.
 *
 * Verification services should build traces through this helper rather than
 * constructing the object literal by hand, so every trace is guaranteed a
 * fresh, correctly-formatted checkedAt timestamp.
 *
 * @param requestId - Correlation id for this verification call.
 * @param fields    - The observed runtime facts for this trace. `checkedAt`
 *                    may be omitted (defaults to now) but may be supplied
 *                    explicitly when the caller wants to backdate to the
 *                    moment the traced operation actually completed.
 */
export function createRuntimeTrace(
  requestId: string,
  fields: Omit<RuntimeTrace, 'requestId' | 'checkedAt'> & { checkedAt?: string }
): RuntimeTrace {
  return {
    requestId,
    checkedAt: fields.checkedAt ?? new Date().toISOString(),
    // Auto-populate the alias fields from their historical counterparts so
    // every call-site written before this revision keeps producing
    // production-grade traces for free, without having to set both names.
    // An explicit value in `fields` always wins (spread below overrides these).
    resolvedProvider: fields.provider,
    resolvedModel: fields.model,
    executionLatency: fields.durationMs,
    ...fields,
  }
}

/**
 * isRuntimeTraceHealthy — minimal pass/fail judgment over a RuntimeTrace,
 * shared by every verify endpoint and by the PowerShell verifier so "healthy"
 * means the same thing everywhere.
 *
 * A trace is healthy when:
 *   - provider and model are both non-empty (something actually served it), and
 *   - IF governance ran (governanceScore is present), the score is >= 0, and
 *     repairAttempts (if present) did not exceed the supplied ceiling, and
 *   - IF persistence was in scope (artifactPersisted is present), it is true.
 *
 * @param trace          - The trace to judge.
 * @param maxRepairAttempts - Repair ceiling to check against (defaults to 3 —
 *                            see runtime_trace.generated.md MAX_REPAIR_ATTEMPTS).
 */
export function isRuntimeTraceHealthy(trace: RuntimeTrace, maxRepairAttempts = 3): boolean {
  if (!trace.provider || !trace.model) return false
  if (typeof trace.governanceScore === 'number' && trace.governanceScore < 0) return false
  if (typeof trace.repairAttempts === 'number' && trace.repairAttempts > maxRepairAttempts) return false
  if (trace.artifactPersisted === false) return false
  return true
}

// ─── RuntimeTrace validation (Part 3 — production-grade evolution) ────────────

/** The 13 fields a production-grade RuntimeTrace is expected to carry. */
export const RUNTIME_TRACE_EXPECTED_FIELDS = [
  'runtimeMode',
  'configuredProvider',
  'resolvedProvider',
  'configuredModel',
  'resolvedModel',
  'fallbackUsed',
  'executionLatency',
  'repairAttempts',
  'governanceScore',
  'brandMemoryApplied',
  'schemaVersion',
  'runtimeVersion',
  'persistenceStatus',
] as const satisfies readonly (keyof RuntimeTrace)[]

export type RuntimeTraceExpectedField = (typeof RUNTIME_TRACE_EXPECTED_FIELDS)[number]

export interface RuntimeTraceFieldIssue {
  /** Field name the issue concerns — one of RUNTIME_TRACE_EXPECTED_FIELDS, or a cross-field label. */
  field: string
  /** 'warn' for a missing/unpopulated field; 'fail' for a genuine internal contradiction. */
  severity: 'warn' | 'fail'
  /** Human-readable explanation — always populated, never a bare boolean. */
  message: string
}

export interface RuntimeTraceValidationResult {
  /** true iff there are zero 'fail'-severity issues. Missing-field WARNs do not affect this. */
  valid: boolean
  issues: RuntimeTraceFieldIssue[]
  /** The full set of fields checked for presence, for report transparency. */
  checkedFields: readonly RuntimeTraceExpectedField[]
}

/**
 * validateRuntimeTrace — Part 3 of the Runtime Verification V2 production-grade
 * evolution. Checks a trace for both PRESENCE (does it carry the 13 expected
 * fields?) and CONSISTENCY (do the fields that are present agree with each
 * other?). Every issue carries a human-readable explanation — this function
 * never collapses its findings into a bare boolean before returning them.
 *
 * Presence gaps are reported as 'warn' — an endpoint that legitimately never
 * touched a subsystem (e.g. a provider-only check has no governanceScore) is
 * not a bug, just an incomplete trace for that check's scope. Genuine
 * contradictions (a field IS present but disagrees with another field that
 * is also present) are reported as 'fail'.
 *
 * @param trace - The trace to validate.
 * @param opts.maxRepairAttempts - Repair ceiling for the repairAttempts
 *   consistency check (defaults to 3 — see EXPECTED_MAX_REPAIR_ATTEMPTS in
 *   apps/web/lib/internal/runtime-verify-service.ts, kept in sync manually).
 */
export function validateRuntimeTrace(
  trace: RuntimeTrace,
  opts: { maxRepairAttempts?: number } = {}
): RuntimeTraceValidationResult {
  const maxRepairAttempts = opts.maxRepairAttempts ?? 3
  const issues: RuntimeTraceFieldIssue[] = []

  for (const field of RUNTIME_TRACE_EXPECTED_FIELDS) {
    const value = trace[field]
    if (value === undefined || value === null || value === ('' as unknown)) {
      issues.push({
        field,
        severity: 'warn',
        message: `'${field}' is not populated on this trace — the check that produced it may not exercise that subsystem, or the endpoint predates this field.`,
      })
    }
  }

  // ── Cross-field consistency ──────────────────────────────────────────────

  if (trace.configuredProvider && trace.resolvedProvider) {
    const providersDiffer = trace.configuredProvider !== trace.resolvedProvider
    if (providersDiffer && trace.fallbackUsed !== true) {
      issues.push({
        field: 'fallbackUsed',
        severity: 'fail',
        message: `resolvedProvider ('${trace.resolvedProvider}') differs from configuredProvider ('${trace.configuredProvider}') but fallbackUsed is not true — a fallback occurred without being recorded as one.`,
      })
    }
    if (!providersDiffer && trace.fallbackUsed === true) {
      issues.push({
        field: 'fallbackUsed',
        severity: 'warn',
        message: `fallbackUsed is true but configuredProvider equals resolvedProvider ('${trace.resolvedProvider}') — no actual fallback is evident.`,
      })
    }
  }

  if (trace.provider && trace.resolvedProvider && trace.provider !== trace.resolvedProvider) {
    issues.push({
      field: 'resolvedProvider',
      severity: 'fail',
      message: `provider ('${trace.provider}') and resolvedProvider ('${trace.resolvedProvider}') disagree — they are meant to be identical aliases.`,
    })
  }

  if (trace.model && trace.resolvedModel && trace.model !== trace.resolvedModel) {
    issues.push({
      field: 'resolvedModel',
      severity: 'fail',
      message: `model ('${trace.model}') and resolvedModel ('${trace.resolvedModel}') disagree — they are meant to be identical aliases.`,
    })
  }

  if (typeof trace.governanceScore === 'number' && (trace.governanceScore < 0 || trace.governanceScore > 100)) {
    issues.push({
      field: 'governanceScore',
      severity: 'fail',
      message: `governanceScore (${trace.governanceScore}) is outside the valid 0–100 range.`,
    })
  }

  if (typeof trace.repairAttempts === 'number' && trace.repairAttempts > maxRepairAttempts) {
    issues.push({
      field: 'repairAttempts',
      severity: 'fail',
      message: `repairAttempts (${trace.repairAttempts}) exceeds the configured ceiling (${maxRepairAttempts}).`,
    })
  }

  if (trace.persistenceStatus === 'persisted' && trace.artifactPersisted === false) {
    issues.push({
      field: 'persistenceStatus',
      severity: 'fail',
      message: `persistenceStatus is 'persisted' but artifactPersisted is false — these must agree.`,
    })
  }
  if (trace.persistenceStatus === 'failed' && trace.artifactPersisted === true) {
    issues.push({
      field: 'persistenceStatus',
      severity: 'fail',
      message: `persistenceStatus is 'failed' but artifactPersisted is true — these must agree.`,
    })
  }

  if (trace.brandMemoryApplied === true && !trace.identityVersion) {
    issues.push({
      field: 'identityVersion',
      severity: 'warn',
      message: `brandMemoryApplied is true but identityVersion was not recorded — expected whenever Brand Memory actually applied an identity.`,
    })
  }

  if (typeof trace.durationMs === 'number' && typeof trace.executionLatency === 'number' && trace.durationMs !== trace.executionLatency) {
    issues.push({
      field: 'executionLatency',
      severity: 'fail',
      message: `durationMs (${trace.durationMs}) and executionLatency (${trace.executionLatency}) disagree — they are meant to be identical aliases.`,
    })
  }

  const hasFail = issues.some(i => i.severity === 'fail')
  return { valid: !hasFail, issues, checkedFields: RUNTIME_TRACE_EXPECTED_FIELDS }
}
